# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Install npm packages
      run: npm install
      working-directory: ${{ matrix.work-dir }}
    - name: Move src/config/prod.ts to src/config/dev.ts
      run: mv src/config/prod.ts src/config/dev.ts
      working-directory: ${{ matrix.work-dir }}
    - name: Run `npm run compile` to compile Typescript into Javascript
      run: npm run compile
      working-directory: ${{ matrix.work-dir }}
    - name: Run `npm test`
      run: npm test
      working-directory: ${{ matrix.work-dir }}
